### ISSUE TITLE
Local playback is not working

### ISSUE THREAD

**Issue by andreskeeled** [Ziggeo/vue-ziggeo#1]
Hello,

After I record a video the loading spinner never disappears. If i try to click on the video I get this error: 

`uncaught exception: Dynamics Exception in 'ZiggeoApi.V2.Player' calling method 'play' : TypeError: this.player is null`

These are my parameters: 

```
 <ziggeo-recorder
      :apiKey="apiKey"
      :timelimit="timeLimit"
      :simulate="true"
      :id="recorderId"
      :width=640
      :height=480
      :theme="'minimalist'"
      :response=true
      :localplayback=true
      :allowupload=false
      :rerecordable=true
      :recordings=2
      @verified="videoRecorded">
    </ziggeo-recorder>
```

Cheers

**Comment by Bane-D** [comment]
Hi Andre,

Can you please tell me if you happen to experience the same without using `simulate` parameter by any chance?

Cheers,
Bane

**Comment by andreskeeled** [comment]
Hi Bane,

Yes, the error appears to persist without the simulate parameter.

Cheers,
Andre

**Comment by Bane-D** [comment]
Hi Andre,

OK, thank you for letting us know.

Now I doubt that the `response` (`responsive`) would cause this since our embeddings can be utilized next to other (custom) IDs, however that is something worth correcting to have it work as you expect.

Would it be possible for us to see the page where this happens? If you do not want to show it publicly, you can send it to our support email and I will find it there. Seems that something causes the switch to fail.

In short the video recorder is turned into player upon recording (or rerecorder per your setup) which should happen right after the `videoRecorded` function is called on your side.

Just for the sake of making sure that it is not causing the issue, would you be OK with checking if same happens for you if you remove the segment declaring your verified event handler - so your code looks like so:

```
 <ziggeo-recorder
      :apiKey="apiKey"
      :timelimit="timeLimit"
      :simulate="true"
      :id="recorderId"
      :width=640
      :height=480
      :theme="'minimalist'"
      :responsive=true
      :localplayback=true
      :allowupload=false
      :rerecordable=true
      :recordings=2>
</ziggeo-recorder>
```
Cheers,
Bane

**Comment by andreskeeled** [comment]
Hello Bane, 

Thank you for bringing to my attention the "response" parameter. I tried removing the verified event handler, and it still crashes. If I remove the localplayback parameter, I just get the "We cannot access this video at the moment. Please try again later. " message. But I guess this is expected since the video is not yet processed.

Also, the page only has the ziggeo-recorder component. Right now, the only logic in this component is to record the video and return the stream token to this component's caller with an event. 

```
<template>
  <div class="recorder">
      <ziggeo-recorder
      :apiKey="apiKey"
      :timelimit="timeLimit"
      :simulate="isTesting"
      :id="recorderId"
      :width=640
      :height=480
      :theme="'minimalist'"
      :response=true
      :localplayback=true
      :allowupload=false
      :rerecordable=true
      :recordings=2
      @verified="videoRecorded">
    </ziggeo-recorder>
  </div>
</template>

<script>
  export default {
    name: 'recorder',
    data () {
      return {
        timeLimit: 30,
        recorderId: 'testingRecorder',
        apiKey: ZIGGEO_API_KEY,
      };
    },
    methods: {
      videoRecorded () {
        // Lets get the ziggeo-recorder element reference
        const element = document.getElementById(this.recorderId);
        const recorder = ZiggeoApi.V2.Recorder.findByElement(element);
        this.$emit(recorder.get('video')); 
      },
    },
  };
</script>
```

Cheers,
Andre

**Comment by sambua** [comment]
Hi Andre,

Sorry, could you please try to re-build(re-compile) bundler after making changes in recorder options/attributes? Because during testing I had the same issue when just try to remove and restore `localplayback` parameter. After a rebuild, it started working as expected.

ZiggeoRecorder component itself also contains player. So, `localplayback` should play inside the recorder component.

Cheers,
Rashad

**Comment by andreskeeled** [comment]
Hello Rashad,

I did as you said and nothing changed. But then I tried in a different browser ( I've been developing in Firefox lately), and everything worked well ( in Chrome). So the problem is probably browser related. 

I will continue my development in Chrome for now, but hopefully this can be fixed for Firefox.

Cheers, 
André

**Comment by andreskeeled** [comment]
No problem Rashad. 

On an unrelated note, how can I set the apiKey for the global instance of the ZiggeoApi, instead of setting the apiKey for each recorder/player? 

I've tried a few ways but none seems to work so far.

Cheers,
André

**Comment by sambua** [comment]
Hi Adré,

You can now test with new version `vue-ziggeo 0.1.0` in FF. 

Regarding global API key. For some reasons, we didn't add it as an option.
But I can advice one option. If you already don't have mixins, you can add in root `main.js` file:

```vue
Vue.mixin({
    data: function () {
        return {
            get globalApiKey() {
                return 'your_const_api_key';
            }
        }
    }
});
```
after you can use in child component 
```vue
<ziggeo-recorder
   :apiKey="globalApiKey"
></ziggeo-recorder>
````

Please just inform me in case if it was solved for you so I could close the issue. Thanks in advance Adré 🙂 

Cheers,
Rashad

**Comment by andreskeeled** [comment]
Hello Sambua,
 
I just tested in Firefox and it's working.

Thanks for you for the quick fix!

Cheers, 
André
