### ISSUE TITLE
Vue 3 Support

### ISSUE THREAD

**Issue by timpulver** [Ziggeo/vue-ziggeo#20]
Would be great if this library would be adapted to work with Vue.js 3. 
[3.0.0-rc.4](https://github.com/vuejs/vue-next/blob/master/CHANGELOG.md) was just released and the API is not supposed to change any more.

**Comment by Bane-D** [comment]
Hi Tim,

Thank you for the suggestion. We do want to support as many frameworks and libraries as our customer's are interested in however at this time we did not hear many customers asking for such update.

The Vue 3.0.0 is also a release candidate at this time, so it is quite likely that we would not be making the switch until it becomes actual release.

I will close this issue since my colleague is already looking into requests for this move and also looking into what is happening in Vue world and will follow up once we do make the move.

Regards,
Bane
