### ISSUE TITLE
Adobe Flash Required?

### ISSUE THREAD

**Issue by raisonon** [Ziggeo/vue-ziggeo#21]
I get this error:

Please click below to install / activate the following requirements in order to proceed.
Adobe Flash

However as I understand Flash is End Of Life -- is this an error? Thanks

**Comment by ntshcalleia** [comment]
Hi @raisonon,

Our recorder uses WebRTC for recording, however if WebRTC is not available it will try other options - including Flash.

Flash is usually used as a fallback when the page is not served over a secure connection (WebRTC can’t record video when the page is loaded using HTTP instead of HTTPS) or on browsers where WebRTC is not supported.

For testing things locally you might want to use a [self-signed certificate](https://letsencrypt.org/docs/certificates-for-localhost/).

**Comment by raisonon** [comment]
That worked - cheers
